tasks:
  - name: terraform
    before: |
      source ./bin/install_terraform_cli
      source ./bin/setup_alias
      source ./bin/tcred_tf_setup
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/install_aws_cli
      source ./bin/setup_alias
      source ./bin/tcred_tf_setup

      cd $THEIA_WORKSPACE_ROOT
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform